parameters:
#    simple_agenda.example.class: HotDesign\SimpleAgendaBundle\Example

services:
#    simple_agenda.example:
#        class: %simple_agenda.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
